-- CREATE DATABASE brand;
USE brand;

-- Creating the THUONGHIEU table
CREATE TABLE THUONGHIEU (
    ID_THUONGHIEU INT AUTO_INCREMENT PRIMARY KEY,
    TENTHUONGHIEU VARCHAR(255) NOT NULL,
    DIACHI VARCHAR(255),
    AVATAR VARCHAR(255)
);

-- Creating the SUKIEN table
CREATE TABLE SUKIEN (
    ID_SUKIEN INT AUTO_INCREMENT PRIMARY KEY,
    ID_THUONGHIEU INT,
    TENSUKIEN VARCHAR(255) NOT NULL,
    HINHANH VARCHAR(255),
    TGBATDAU DATETIME,
    TGKETTHUC DATETIME,
    LOAITROCHOI VARCHAR(255)
);

-- Creating the VOUCHER table
CREATE TABLE VOUCHER (
    ID_VOUCHER INT AUTO_INCREMENT PRIMARY KEY,
    ID_THUONGHIEU INT,
    NGAYHETHAN DATETIME,
    TRIGIA INT,
    TRANGTHAI VARCHAR(50),
    HINHANH VARCHAR(255),
    QRCODE VARCHAR(255),
    MOTA TEXT
);

-- Creating the VOUCHER_SUKIEN table
CREATE TABLE VOUCHER_SUKIEN (
    ID_VOUCHER INT,
    ID_SUKIEN INT,
    SOLUONGVOUCHER INT,
    SOLUOTSUDUNG INT,
    TRANGTHAI VARCHAR(50),
    PRIMARY KEY (ID_VOUCHER, ID_SUKIEN)
);
